services:
  postgres:
    container_name: threads-db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: threads
      POSTGRES_DB: threads  
    

volumes:
  postgres_data: 
